name: pangolin_example
description: Demonstrates how to use the pangolin plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  permission_handler: ^5.0.0+hotfix.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  pangolin:
    path: ../

flutter:
  uses-material-design: true