name: pangolin
description: Flutter plugin for bytedance Ad SDK.
version: 0.1.4
authors:
  - tongyangsheng<dream.master.tong@gmail.com>
homepage: https://github.com/tongyangsheng/Pangolin.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.tongyangsheng.pangolin
    pluginClass: PangolinPlugin

